version: '3'
services:
  myyoutube:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8082:5000"